[vm]
20.151.117.2 ansible_user=azureuser ansible_ssh_private_key_file=../Terraform/id_rsa.pem

[acr]
localhost ansible_connection=local ansible_python_interpreter=/home/magdiel/.pyenv/versions/3.10.13/bin/python